# Generated by Django 5.0.3 on 2024-05-07 10:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dept',
            fields=[
                ('D_deptno', models.IntegerField(primary_key=True, serialize=False)),
                ('D_loc', models.CharField(max_length=20, unique=100)),
                ('D_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Salgrade',
            fields=[
                ('Grade', models.IntegerField(primary_key=True, serialize=False)),
                ('Hisal', models.DecimalField(decimal_places=2, max_digits=8)),
                ('Losal', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='Emp',
            fields=[
                ('Emp_no', models.IntegerField(max_length=20, primary_key=True, serialize=False)),
                ('Emp_name', models.CharField(max_length=20)),
                ('job', models.CharField(max_length=100)),
                ('Sal', models.DecimalField(decimal_places=2, max_digits=8)),
                ('Commi', models.DecimalField(decimal_places=2, max_digits=8)),
                ('Hiredate', models.DateField()),
                ('Deptno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.dept')),
                ('Mgr', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.emp')),
            ],
        ),
    ]
